### ISSUE TITLE
Your deployed app (and main!) is no longer working!!

### ISSUE THREAD

**Issue by madsnedergaard** [MariusAlba/Danish-Around-Town#14]
Hey team,

We've been looking at your code today and it seems like there's some issues that were introduced 3 days ago.

Your deployed app that is linked in the report + the `main` branch is out of date and shows hardcoded images: https://github.com/MariusAlba/Danish-Around-Town/blob/main/src/Flipcard.js

**Please update the branch and deploy the latest version!**

There's also another issue (maybe only on `development` branch) - the file `src/convert.js` should start with capital `C`:

<img width="815" alt="Screenshot 2021-01-14 at 17 02 47" src="https://user-images.githubusercontent.com/3296643/104618301-cecec680-568c-11eb-93d1-37257c6a3599.png">

Please fix this if you want to ensure your censor sees the correct version of your app where image upload works! :)

@MariusAlba @aiza2omar @sealpuppy @yjyin19

**Comment by MariusAlba** [comment]
We fixed the problem but we forgot to deploy it. We are trying to make it
now as fast as possible.

**Comment by MariusAlba** [comment]
Hi Mads, 

We have fixed and deployed the code. 
You are welcome to check it

**Comment by madsnedergaard** [comment]
Great, it works fine for me now - thanks for the quick fix! 💪

**Comment by MariusAlba** [comment]
No, thank you Mads for letting us know of this issue. Have a relaxing
weekend
